#trigger:
#- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetCommand@2
  displayName: Nuget Pack
  inputs:
    command: 'pack'
    packagesToPack: 'TestCodeAnalyser.csproj'
    versioningScheme: byBuildNumber
